language: swift
os: osx
osx_image: xcode11.5
xcode_workspace: ./wallet/wallet.xcworkspace
xcode_scheme: wallet
xcode_destination: platform=iOS Simulator,OS=13.2.2,name=iPhone 8
addons:
  homebrew:
    packages:
    - rustup-init
    - sourcery
env:
  global:
  - ZCASH_NETWORK_ENVIRONMENT: TESTNET
install:
  - ${TRAVIS_BUILD_DIR}/Scripts/travis/rust_setup.sh
  - WALLET_DIR=${TRAVIS_BUILD_DIR}/wallet
  - WALLET_WALLET_DIR=${WALLET_DIR}/wallet
  - cp ${WALLET_DIR}/env-vars.sh.example ${WALLET_DIR}/env-vars.sh
  - cd ${WALLET_DIR} ; pod install ; cd ${TRAVIS_BUILD_DIR}
script:
  - travis_wait 60 xcodebuild -quiet -workspace ${TRAVIS_BUILD_DIR}/wallet/wallet.xcworkspace -scheme wallet -destination platform\=iOS\ Simulator,OS\=13.2.2,name\=iPhone\ 8 build test
