language: swift
os: osx
osx_image: xcode12
xcode_workspace: ./wallet/ECC-Wallet.xcworkspace
xcode_scheme: ECC-Wallet
xcode_destination: platform=iOS Simulator,OS=14.0,name=iPhone 8
addons:
  homebrew:
    packages:
    - rustup-init
    - sourcery
env:
  global:
  - ZCASH_NETWORK_ENVIRONMENT: TESTNET
install:
  - ${TRAVIS_BUILD_DIR}/Scripts/travis/rust_setup.sh
  - WALLET_DIR=${TRAVIS_BUILD_DIR}/wallet
  - WALLET_WALLET_DIR=${WALLET_DIR}/wallet
  - cp ${WALLET_DIR}/env-vars.sh.example ${WALLET_DIR}/env-vars.sh
  - cd ${WALLET_DIR} ; pod install ; cd ${TRAVIS_BUILD_DIR}
  - curl https://download.z.cash/downloads/sapling-output.params > ${WALLET_WALLET_DIR}/sapling-output.params
  - curl https://download.z.cash/downloads/sapling-spend.params > ${WALLET_WALLET_DIR}/sapling-spend.params


script:
  - set -o pipefail && xcodebuild -version
  - set -o pipefail && xcodebuild -showsdks 
  - travis_wait 60 xcodebuild -quiet -workspace ${TRAVIS_BUILD_DIR}/wallet/ECC-Wallet.xcworkspace -scheme ECC-Wallet-no-logging -destination platform\=iOS\ Simulator,OS\=14.0,name\=iPhone\ 8 build
