language: swift
os: osx
osx_image: xcode11.5
xcode_workspace: ./wallet/wallet.xcworkspace
xcode_scheme: wallet
xcode_destination: platform=iOS Simulator,OS=13.2.2,name=iPhone 8
install:
  - cd ${TRAVIS_BUILD_DIR}/wallet
  - pod install
script:
  - xcodebuild -workspace ${TRAVIS_BUILD_DIR}/wallet/wallet.xcworkspace -scheme wallet -destination platform\=iOS\ Simulator,OS\=13.2.2,name\=iPhone\ 8 build test
