platform :ios, '13.0'
use_frameworks!

target 'wallet' do 
 pod 'ZcashLightClientKit',  :path => '/Users/pacu/Repos/ECC/ZcashLightClientKit'
 pod 'KeychainSwift', '~> 19.0.0'
 pod 'MnemonicKit', :git => 'git@github.com:pacu/MnemonicKit.git', :branch => 'CriptoKit'
 pod 'TinyQRScanner'
 pod 'lottie-ios'
 target 'walletTests' do 
  inherit! :search_paths
 end
 
 target 'walletUITests' do 
   inherit! :search_paths
 end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|


      if target.name == 'ZcashLightClientKit'
         config.build_settings['ZCASH_NETWORK_ENVIRONMENT'] = ENV["ZCASH_NETWORK_ENVIRONMENT"]
      end
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
