platform :ios, '13.0'
use_frameworks!

def base_pods
  pod 'ZcashLightClientKit', '~> 0.6.0'
  pod 'gRPC-Swift', '= 1.0.0-alpha.17'
  pod 'KeychainSwift', '~> 19.0.0'
  pod 'MnemonicSwift'
  pod 'TinyQRScanner'
  pod 'lottie-ios'
end

inhibit_all_warnings!

target 'ECC-Wallet-no-logging' do
  base_pods
end

target 'ECC-Wallet' do 
  base_pods
  pod 'Mixpanel-swift'
  pod 'Bugsnag'
  target 'ECC-WalletTests' do
    inherit! :search_paths
  end
 
  target 'ECC-WalletUITests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|


      if target.name == 'ZcashLightClientKit'
         config.build_settings['ZCASH_NETWORK_ENVIRONMENT'] = ENV["ZCASH_NETWORK_ENVIRONMENT"]
      end
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
